function Player_ChoosingCharacterState_EditingCharacterInventory_update(player: player, isHovering: boolean):
  if {_isHovering} is true:
    # Edit
    set {_edit} to player head named "&fРедактировать поле"
    add "{SkullOwner:{Id:""538a7620-6569-4421-8675-7261b22a7617"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTdlZDY2ZjVhNzAyMDlkODIxMTY3ZDE1NmZkYmMwY2EzYmYxMWFkNTRlZDVkODZlNzVjMjY1ZjdlNTAyOWVjMSJ9fX0=""}]}}}" to item-nbt of {_edit}

    add {_edit} to {_items::*}
  else:
    # Play
    set {_play} to player head named "Играть за этого персонажа"
    add "{SkullOwner:{Id:""fd0c2633-9fdb-4049-87fb-222616d96066"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZmE4ZjZiMTMxZWY4NDdkOTE2MGU1MTZhNmY0NGJmYTkzMjU1NGQ0MGMxOGE4MTc5NmQ3NjZhNTQ4N2I5ZjcxMCJ9fX0=""}]}}}" to item-nbt of {_play}

    add {_play} to {_items::*}

  # Go back
  set {_back} to player head named "&fНазад к списку персонажей"
  add "{SkullOwner:{Id:""bbf760b3-5f9c-44ae-a84a-06f4314c935e"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZWRmNWMyZjg5M2JkM2Y4OWNhNDA3MDNkZWQzZTQyZGQwZmJkYmE2ZjY3NjhjODc4OWFmZGZmMWZhNzhiZjYifX19""}]}}}" to item-nbt of {_back}

  add {_back} to {_items::*}

  # Getting itemslots for this items array
  set {_itemSlots::*} to Helper_getSlotsForItems(size of {_items::*})

  # Empty items
  set {_empty} to air

  loop numbers from 0 to 8:
    if {_itemSlots::*} doesn't contain loop-value:
      set slot loop-value of {_player}'s inventory to {_empty}

  # Hotbar items
  loop {_items::*}:
    set {_slot} to first element of {_itemSlots::*}
    remove {_slot} from {_itemSlots::*}

    set slot {_slot} of {_player}'s inventory to loop-value