test:
  zone:
    center: -100, 20, 300
    borders:
    - -10, 20, 300
    - 10, 20, -300
    places:
      test:
        type: bus
        coords: -100, 20, 300
      
      test2:
        type: bus
        coords: -100, 20, 300